-- "Sequence for adding tables to db:
-- 1.  users
-- 2.  classes
-- 3.  sections
-- 4.  subjects
-- 5.  questiontype
-- 6.  topics
-- 7.  classes_taught_by_teacher
-- 8.  studentDetails
-- 9.  questionbank
-- 10. assessments
-- 11. assessment_questions
-- 12. deploymentlog
-- 13. todolist"

-- 1.  users
-- All users - including SuperAdmin(Z), Admins(A), Teachers(T) and Students(S)
CREATE TABLE `users` (
  `userId` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `role` set('A','S','T','Z') NOT NULL,
  `firstName` varchar(50) NOT NULL,
  `middleName` varchar(25) DEFAULT NULL,
  `lastName` varchar(50) NOT NULL,
  `Email` varchar(50) DEFAULT NULL,
  `systemEmail` varchar(50) NOT NULL COMMENT 'This will be auto generated by the system',
  `pw` varchar(50) NOT NULL,
  `joinYear` varchar(25) DEFAULT NULL,
  `endYear` varchar(25) DEFAULT NULL,
  `phoneMobile` varchar(15) NOT NULL,
  `visibility` set('Y','N') NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 2.  classes
-- 1=I, 2=II, 3=III, 4=IV, 5=V.....
CREATE TABLE `classes` (
  `classId` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `classNumber` varchar(5) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 3.  sections
-- 1=A, 2=B, 3=C...
CREATE TABLE `sections` (
  `sectionId` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `sectionName` varchar(5) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 4.  subjects
-- 1=Hindi, 2=English....
CREATE TABLE `subjects` (
  `subjectId` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `subjectName` varchar(20) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 5.  questiontype
-- 1=LTA=Long Type Answers, 2=MCQ=Multiple Choice Questions...
CREATE TABLE `questiontype` (
  `qtId` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `typeName` varchar(50) NOT NULL UNIQUE,
  `Description` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 6.  topics
CREATE TABLE `topics` (
  `topicId` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `classId` int(11) NOT NULL,
  `subjectId` int(11) NOT NULL,
  `topicName` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 7.  classes_taught_by_teacher
CREATE TABLE `classes_taught_by_teacher` (
  `cttId` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `userId` int(11) NOT NULL,
  `classId` int(11) NOT NULL,
  `sectionId` int(11) NOT NULL,
  `subjectId` int(11) NOT NULL,
  UNIQUE `teacherClassId` (`userId`,`classId`,`sectionId`,`subjectId`),
  CONSTRAINT `Class Number` FOREIGN KEY (`classId`) REFERENCES `classes` (`classId`),
  CONSTRAINT `Section` FOREIGN KEY (`sectionId`) REFERENCES `sections` (`sectionId`),
  CONSTRAINT `Subject` FOREIGN KEY (`subjectId`) REFERENCES `subjects` (`subjectId`),
  CONSTRAINT `Teacher` FOREIGN KEY (`userId`) REFERENCES `users` (`userId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 8.  studentDetails
CREATE TABLE `studentdetails` (
  `userId` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `rollNumber` int(11) NOT NULL,
  `classId` int(11) DEFAULT NULL,
  `sectionId` int(11) DEFAULT NULL,
  CONSTRAINT `User Id` FOREIGN KEY (`userId`) REFERENCES `users` (`userId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 9.  questionbank
CREATE TABLE `questionbank` (
  `qId` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `classId` int(11) NOT NULL,
  `subjectId` int(11) NOT NULL,
  `topicId` int(11) NOT NULL,
  `typeId` int(11) NOT NULL,
  `question` varchar(1000) NOT NULL,
  `Option_1` varchar(50) NOT NULL,
  `Option_2` varchar(50) NOT NULL,
  `Option_3` varchar(50) NOT NULL,
  `Option_4` varchar(50) NOT NULL,
  `Option_5` varchar(50) NOT NULL,
  `Option_6` varchar(50) NOT NULL,
  -- CONSTRAINT `Subject` FOREIGN KEY (`subjectId`) REFERENCES `subjects` (`subjectId`),
  CONSTRAINT `Class` FOREIGN KEY (`classId`) REFERENCES `classes` (`classId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 10. assessments
-- only id and title, questions in assessment_questions table
CREATE TABLE `assessments` (
  `assessment_Id` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `assessment_Title` varchar(250) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 11. assessment_questions
-- maps assessment id to question id from questionbank
CREATE TABLE `assessment_questions` (
  `assessment_Id` int(11) NOT NULL,
  `question_id` int(11) NOT NULL,
  CONSTRAINT `Assessment Id` FOREIGN KEY (`assessment_Id`) REFERENCES `assessments` (`assessment_Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 12. deploymentlog
-- maps deployment id to assessment id, can have multiple entries for assessment id
CREATE TABLE `deploymentlog` (
  `depId` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `depType` set('A','Q','T') NOT NULL ,
  `sectionId` int(11) NOT NULL,
  `assessmentId` int(11) NOT NULL,
  `schStartDate` date NOT NULL ,
  `schEndDate` date NOT NULL ,
  `autoReminderDays` tinyint(3) NOT NULL ,
  `deploySuccess` tinyint(1) NOT NULL DEFAULT '0' ,
  UNIQUE `Dedupe` (`assessmentId`,`depType`,`schStartDate`,`sectionId`),
  CONSTRAINT `AssessmentId` FOREIGN KEY (`assessmentId`) REFERENCES `assessments` (`assessment_Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 13. todolist
-- teacher's notes to himself/herself
CREATE TABLE `todolist` (
  `userId` int(11),
  `todoId` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `todoText` varchar(255) NOT NULL UNIQUE,
  CONSTRAINT `User Id` FOREIGN KEY (`userId`) REFERENCES `users` (`userId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;








-- this table became redundant after merging all users into user table
-- CREATE TABLE `teachers` (
--   `teacherId` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
--   `firstName` varchar(25) NOT NULL,
--   `middleName` varchar(25) DEFAULT NULL,
--   `lastName` varchar(25) NOT NULL,
--   `Email` varchar(50) NOT NULL,
--   `systemEmail` varchar(50) NOT NULL,
--   `phoneNumber` varchar(50) NOT NULL,
--   `joinYear` varchar(4) DEFAULT NULL,
--   `leftYear` varchar(4) DEFAULT NULL,
--   `visibility` set('Y','N') NOT NULL,
--   CONSTRAINT `User Id` FOREIGN KEY (`userId`) REFERENCES `users` (`userId`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8;







-- --
